### ISSUE TITLE
Preallocate slices demo snippet has a mistaken

### ISSUE THREAD

**Issue by barryz** [davecheney/gophercon2018-performance-tuning-workshop#7]
Article: 6-tips-and-tricks/1-tips-and-tricks.md
Section: Preallocate slices if the length is known

Wrong demo: 

```go
vals := fn()
s := make([]string, len(vals))  // should pre-allocate the capacity of slice.
for i, v := range vals {
        s[i] = v
}
return s
```

Right demo:

```go
vals := fn()
s := make([]string, 0, len(vals))  // should pre-allocate the capacity of slice.
for i, v := range vals {
        s[i] = v
}
return s
```

**Comment by Quasilyte** [comment]
@barryz, the proposed "right" version will panic due to out-of-range access.

The capacity pre-allocation should be used with `append` without direct index assignment.
Initial demo does the length-based pre-allocation with index assignment.

See https://play.golang.org/p/b1T5JU6T2DQ

If you agree, this issue should be closed.

**Comment by barryz** [comment]
okay, i will close the issue.
